--DROP DATABASE LABORMED
--CREATE DATABASE LABORMED
/*
DROP TABLE PRODUTO
DROP TABLE FABRICANTE
DROP TABLE SUBGRUPO
DROP TABLE GRUPO
DROP TABLE USUARIO
*/

USE LABORMED

CREATE TABLE USUARIO (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL,
	SOBRENOME VARCHAR(30) NOT NULL,
	LOGIN VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(60) NOT NULL,
	SENHA VARCHAR(30) NOT NULL,
	DATA_REG DATE NOT NULL,
	ATIVO BIT
)

CREATE TABLE FABRICANTE (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	DATA_REG DATE NOT NULL,
	RAZAO_SOCIAL VARCHAR(30) NOT NULL,
	CNPJ VARCHAR(18) NOT NULL,
	ENDERECO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO VARCHAR(30) NOT NULL,
	TELEFONE VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	CONTATO VARCHAR(30) NOT NULL
)

CREATE TABLE GRUPO (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	DESCRICAO VARCHAR(60) NOT NULL,
)

CREATE TABLE SUBGRUPO (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	DESCRICAO VARCHAR(60) NOT NULL,
	ID_GRUPO BIGINT NOT NULL,
	FOREIGN KEY (ID_GRUPO) REFERENCES dbo.GRUPO (ID) ON UPDATE NO ACTION ON DELETE CASCADE
)


CREATE TABLE PRODUTO (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	DESCRICAO VARCHAR(60) NOT NULL,
	CODIGO VARCHAR(30) NOT NULL,
	CODIGO_BARRAS VARCHAR(30) NOT NULL,
	DATA_REG DATE NOT NULL,
	REGISTRO_ANVISA VARCHAR(30) NOT NULL,
	ID_FABRICANTE BIGINT NOT NULL,
	ID_SUBGRUPO BIGINT NOT NULL,
	ID_USUARIO_CADASTRO BIGINT NOT NULL,
	ATIVO BIT,
	FOREIGN KEY (ID_FABRICANTE) REFERENCES dbo.FABRICANTE (ID) ON UPDATE NO ACTION ON DELETE CASCADE,
	FOREIGN KEY (ID_SUBGRUPO) REFERENCES dbo.SUBGRUPO (ID) ON UPDATE NO ACTION ON DELETE CASCADE,
	FOREIGN KEY (ID_USUARIO_CADASTRO) REFERENCES dbo.USUARIO (ID) ON UPDATE NO ACTION ON DELETE CASCADE
)

-- DADOS
INSERT INTO USUARIO VALUES('Paulo', 'Nicolau', 'admin', 'paulonicolau@oi.com.br', 'admin', getDate(), 1)

INSERT INTO GRUPO VALUES ('Material de coleta')
INSERT INTO GRUPO VALUES ('Tubo')
INSERT INTO GRUPO VALUES ('Reagente')
INSERT INTO GRUPO VALUES ('Diversos')

--GRUPO 1
INSERT INTO SUBGRUPO VALUES ('Agulha 20 x 0,55 (roxa)', 1)
INSERT INTO SUBGRUPO VALUES ('Agulha 25 x 7 vácuo preta', 1)
INSERT INTO SUBGRUPO VALUES ('Agulha 25 x 8 vácuo verde', 1)
INSERT INTO SUBGRUPO VALUES ('Agulha 25 x 7', 1)
INSERT INTO SUBGRUPO VALUES ('Agulha 25 x 8', 1)
INSERT INTO SUBGRUPO VALUES ('Alcool', 1)
INSERT INTO SUBGRUPO VALUES ('Algodão', 1)
INSERT INTO SUBGRUPO VALUES ('Curativo Adulto', 1)
INSERT INTO SUBGRUPO VALUES ('Curativo Infantil', 1)
INSERT INTO SUBGRUPO VALUES ('Destrosol', 1)
INSERT INTO SUBGRUPO VALUES ('Especulo M', 1)
INSERT INTO SUBGRUPO VALUES ('Especulo G', 1)
INSERT INTO SUBGRUPO VALUES ('Especulo P', 1)
INSERT INTO SUBGRUPO VALUES ('Garrote', 1)
INSERT INTO SUBGRUPO VALUES ('Lactose', 1)
INSERT INTO SUBGRUPO VALUES ('Lamina de Bisturi', 1)
INSERT INTO SUBGRUPO VALUES ('Luva G', 1)
INSERT INTO SUBGRUPO VALUES ('Luva M', 1)
INSERT INTO SUBGRUPO VALUES ('Luva P', 1)
INSERT INTO SUBGRUPO VALUES ('Placa Petri', 1)
INSERT INTO SUBGRUPO VALUES ('Scalp', 1)
INSERT INTO SUBGRUPO VALUES ('Seringa 10 ml', 1)
INSERT INTO SUBGRUPO VALUES ('Seringa 20 ml', 1)
INSERT INTO SUBGRUPO VALUES ('Seringa 5 ml', 1)
INSERT INTO SUBGRUPO VALUES ('Seringa de insulina', 1)

--GRUPO 2
INSERT INTO SUBGRUPO VALUES ('Tubo de EDTA', 2)
INSERT INTO SUBGRUPO VALUES ('Tubo de 8 ml', 2)
INSERT INTO SUBGRUPO VALUES ('Tubo de 4 ml', 2)
INSERT INTO SUBGRUPO VALUES ('Tubo de citrato', 2)

--GRUPO 3
INSERT INTO SUBGRUPO VALUES ('Bioquimica', 3)
INSERT INTO SUBGRUPO VALUES ('Hematologia', 3)
INSERT INTO SUBGRUPO VALUES ('Imunologia', 3)
INSERT INTO SUBGRUPO VALUES ('Corante', 3)
INSERT INTO SUBGRUPO VALUES ('Urianalise', 3)
INSERT INTO SUBGRUPO VALUES ('Parasito', 3)

--GRUPO 4
INSERT INTO SUBGRUPO VALUES ('Caixa Coletor Perfuro Cortante', 4)
INSERT INTO SUBGRUPO VALUES ('Saco de Lixo branco/hospitalar', 4)
INSERT INTO SUBGRUPO VALUES ('Gazes', 4)
INSERT INTO SUBGRUPO VALUES ('Coletor de Urina 50 ml', 4)
INSERT INTO SUBGRUPO VALUES ('Coletor de Urina 3 L - 24 horas', 4)
INSERT INTO SUBGRUPO VALUES ('Ponteira Azul', 4)
INSERT INTO SUBGRUPO VALUES ('Ponteira Amarela', 4)
INSERT INTO SUBGRUPO VALUES ('Laminula', 4)
INSERT INTO SUBGRUPO VALUES ('Lençol de papel', 4)
INSERT INTO SUBGRUPO VALUES ('Laminula para microscopia', 4)

--FABRICANTES
INSERT INTO FABRICANTE VALUES (getDate(), 'RAZAO_SOCIAL', 'CNPJ', 'ENDERECO', 'Rio de Janeiro', 'RJ', '21998050515', 'fabricante@ddd.com.br', 'Adalberto')

--PRODUTOS
INSERT INTO PRODUTO VALUES ('Acido Urico', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Albumina', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Amilase', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Bilirrubina', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Colesterol Total', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Colesterol HDL', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Calcio', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Creatinina', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('CK', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Ferro', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Fosfatase Alcalina', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Fosforo', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Gama GT', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Glicose', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Proteina Total', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Ast - TGO Cinetico', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Alt - TGP Cinetico', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Triglicerides', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Ureia', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Magnesio', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Potassio', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Sodio', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Hemoglobina Glicada', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Integra Cleaner', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Fluid Pack', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Precicontrol', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Cefas', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)
INSERT INTO PRODUTO VALUES ('Bobina de papel', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 1, 1, 1)

INSERT INTO PRODUTO VALUES ('Imunologia', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('HIV 1/2', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('HCG 25 UI', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('HBSAG', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('Sangue Oculto C/Dieta', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('HCV', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('Dengue IGG/IGM', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('Dengue NS1', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('Cocaina', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('Maconha', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('PCR - Latex', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('Fator Reumatoíde', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('ASLO', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('Proteinuria', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('Anti A', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('Anti B', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)
INSERT INTO PRODUTO VALUES ('Anti D', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 2, 1, 1)

INSERT INTO PRODUTO VALUES ('Pipeta de VHS', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 3, 1, 1)
INSERT INTO PRODUTO VALUES ('Controle KX', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 3, 1, 1)
INSERT INTO PRODUTO VALUES ('CellPack 20 L', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 3, 1, 1)
INSERT INTO PRODUTO VALUES ('Stromatolyser', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 3, 1, 1)
INSERT INTO PRODUTO VALUES ('Bobina de papel', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 3, 1, 1)

INSERT INTO PRODUTO VALUES ('Meio de cultura', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 4, 1, 1)
INSERT INTO PRODUTO VALUES ('Fita de Urina', 'CODIGO', 'CODIGO_BARRAS', getDate(), 'REGISTRO_ANVISA', 1, 4, 1, 1)
